services:
  db:
    container_name: postgres
    image: postgres:17.6
    environment:
      POSTGRES_USER: ltt4456
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge

volumes:
  db:
